version: "3.5"
services:
  tenerife_db:
    container_name: tenerife_db
    build:
      context: database/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: tenerife_db
      POSTGRES_USER: tenerife_db
      POSTGRES_PASSWORD: basaltic
    ports:
      - "5446:5432"
    networks:
      - tenerife_db
    volumes:
      - tenerife-pg_data:/var/lib/postgresql/data

  tenerife_website:
    container_name: tenerife_website
    command: gunicorn --bind 0.0.0.0:5000 main:app
    env_file:
      - ./.env.prod
    build:
      context: web_master/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - tenerife_db
    networks:
      tenerife_db:
    volumes:
      - ./web_master/website:/opt/tenerife/website

networks:
  tenerife_db:

volumes:
  tenerife-pg_data:

